from __future__ import annotations

DEFAULT_BAUDRATE = 115200
DEFAULT_RUN_TIMEOUT_SEC = 0
RUN_FAILURE_FRIENDLY_REPL_TIMEOUT_SEC = 2.5
RUN_FAILURE_SOFT_RESET_TIMEOUT_SEC = 12.0
RAW_REPL_CHUNK_BYTES = 1024
RAW_REPL_CHUNK_DELAY_SEC = 0.00
RAW_REPL_ENTER_TIMEOUT_SEC = 6.0
RAW_REPL_EXIT_TIMEOUT_SEC = 2.0
RAW_REPL_CANCEL_TIMEOUT_SEC = 5.0
RAW_REPL_BANNER = b"raw REPL; CTRL-B to exit\r\n"
RAW_REPL_PROMPT = RAW_REPL_BANNER + b">"
FRIENDLY_PASTE_ENTER_TIMEOUT_SEC = 1.5
FRIENDLY_PASTE_RECOVERY_TIMEOUT_SEC = 2.0
FRIENDLY_PASTE_PROMPT = b"=== "
FRIENDLY_PASTE_CHUNK_BYTES = 256
FRIENDLY_PASTE_CHUNK_DELAY_SEC = 0.01
PORT_OPEN_SETTLE_SEC = 0.12
READER_PAUSE_WAIT_SEC = 2.0
SOFT_RESET_BREAK_DELAY_SEC = 0.05
SOFT_RESET_TIMEOUT_FALLBACK_SEC = 2.5
SYNC_DEVICE_COMMAND_TIMEOUT_SEC = 15.0
SYNC_DIR_COMMAND_TIMEOUT_SEC = 6.0
SYNC_SCAN_COMMAND_TIMEOUT_SEC = 25.0
SYNC_FILE_SCRIPT_CHUNK_BYTES = 1024
SYNC_SIGNATURE_SCAN_TIMEOUT_SEC = 60.0
SYNC_FILE_UPLOAD_TIMEOUT_SEC = 5.0
SYNC_REPL_DELAY_SEC = 0.00
SYNC_FILE_RETRY_COUNT = 2
SYNC_FILE_RETRY_DELAY_SEC = 0.2
SYNC_FILE_RETRY_RECONNECT_DELAY_SEC = 3.0
SYNC_FAST_COMPARE_TARGET_SEC = 5.0
SYNC_DYNAMIC_RECENT_WINDOW_SEC = 300.0
SYNC_DYNAMIC_SIGNATURE_MARGIN_SEC = 0.35
SYNC_DYNAMIC_SIGNATURE_BYTES_PER_SEC = 32768.0
SYNC_DYNAMIC_MAX_SIGNATURE_FILES = 64
SYNC_UPLOAD_ONLY_FAST_SCAN_MIN_FILES = 32
SYNC_UPLOAD_ONLY_FAST_SCAN_MAX_FILES = 512
SYNC_TARGETED_SCAN_BATCH_SIZE = 64
SYNC_TARGETED_SCAN_MAX_SCRIPT_CHARS = 2600
SYNC_TARGETED_VERIFY_MAX_FILES = 64
SYNC_TARGETED_VERIFY_TIMEOUT_SEC = 8.0
SYNC_CLEAR_ALL_TIMEOUT_SEC = 60.0
WORKSPACE_IMPORT_FILE_CHUNK_BYTES = 128
WORKSPACE_READ_FILE_CHUNK_BYTES = 48
WORKSPACE_READ_TEXT_CHUNK_CHARS = 256
WORKSPACE_IMPORT_FILE_TIMEOUT_MAX_SEC = 90.0
WORKSPACE_IMPORT_FILE_THROUGHPUT_BYTES_PER_SEC = 4096.0
SOFT_RESET_REBOOT_MARKERS = (
    b"soft reboot",
    b"Triple Boot System",
    b"free ram initially=",
)
COMMAND_PRIORITY = {
    "session.open": 5,
    "terminal.write": 6,
    "run-file-interactive": 9,
    "run-file": 10,
    "sync-folder": 11,
    "clear-all-files": 11,
    "workspace.scan-tree": 11,
    "workspace.list-directory": 11,
    "workspace.stat": 11,
    "workspace.statvfs": 11,
    "workspace.read-file": 11,
    "workspace.write-file": 11,
    "workspace.create-directory": 11,
    "workspace.delete": 11,
    "workspace.rename": 11,
    "workspace.sync": 11,
    "workspace.import": 11,
    "soft-reset": 20,
    "session.close": 25,
    "session.state": 30,
    "scan": 90,
    "shutdown": 99,
}
BACKEND_WRITE_RETRIES = 3
EVENT_SESSION = "session"
EVENT_TERMINAL_OUTPUT = "terminal-output"
FRIENDLY_REPL_PROMPTS = (b">>>", b"...")

__all__ = [name for name in globals() if name.isupper()]
